-- =============================================================================
-- FORGE Enterprise AlignmentOS — Retool source schema (enriched)
-- Source:    Retool managed PostgreSQL (production), schema = public
-- Extracted: 1 May 2026
-- Method:    information_schema + pg_catalog queries (5 separate)
-- 
-- CONTENT:
--   - 71 base tables with full DDL: columns, types, NOT NULL, defaults
--   - Primary keys (71 tables; 2 entries are VIEWS without PKs — see notes)
--   - Foreign keys (92 relationships) — added as ALTER TABLE statements
--   - Unique constraints (28) — added as ALTER TABLE statements
--   - Check constraints (47) — added as ALTER TABLE statements
--   - Indexes (31, excluding PK/UQ-implicit indexes) — added as CREATE INDEX
-- 
-- NOTES FOR CURSOR / IMPLEMENTER:
-- 1. The objects "os_poti_scopes_all" and "risks_with_rag" appear in this file
--    as CREATE TABLE statements but they have no primary key and no NOT NULL
--    constraints on identity columns. They are almost certainly VIEWS in the
--    source database that the meta-query rendered as tables. In the Supabase
--    migration these should be recreated as CREATE VIEW (or MATERIALIZED VIEW)
--    based on their underlying tables. Do NOT migrate them as base tables.
--    Their definitions are not in this file — query Retool's pg_views to
--    capture them, or reconstruct from semantics.
-- 
-- 2. Foreign key ON UPDATE / ON DELETE rules are captured in the FK section.
-- 
-- 3. Sequences: there are no SERIAL/IDENTITY sequences in this schema; all
--    auto-generated keys use gen_random_uuid().
-- 
-- 4. Triggers and functions are NOT captured here. If the source uses any
--    (e.g. updated_at auto-update triggers), they need to be queried separately
--    via pg_trigger / pg_proc.
-- 
-- 5. RLS: no RLS policies exist in source. They are to be ADDED in the Supabase
--    migration per Architecture Blueprint Section 2 / Section 3.
-- 
-- 6. The org_id column is present on most tenant-scoped tables already — this
--    is a major head start for RLS. Reference data tables (os_*, delivery_model_*,
--    benchmark_ranges, rag_thresholds, governance_matrix, field_guidance,
--    artefact_types) have NO org_id and are global. RLS on those should be
--    "read-allowed for all authenticated users, write restricted to service role".
-- 
-- 7. DO NOT apply this file directly to Supabase. It documents the SOURCE state.
--    The Supabase migration files (with org_id additions where missing, RLS,
--    the 10 new tables from the Blueprint) will be generated by Cursor as
--    separate migration files.
-- =============================================================================

-- =============================================================================
-- SECTION 1: CREATE TABLE statements (columns, types, NOT NULL, defaults)
-- =============================================================================


CREATE TABLE "public"."activity_log" (
  "log_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "user_id" UUID,
  "entity_type" TEXT NOT NULL,
  "entity_id" UUID NOT NULL,
  "action" TEXT NOT NULL,
  "old_values" JSONB,
  "new_values" JSONB,
  "ip_address" TEXT,
  "user_agent" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."actuals" (
  "actual_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "budget_id" UUID,
  "transaction_date" DATE NOT NULL,
  "description" TEXT,
  "amount_gbp" NUMERIC(15,2) NOT NULL,
  "invoice_reference" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT
);

CREATE TABLE "public"."artefact_types" (
  "artefact_type_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "type_code" TEXT NOT NULL,
  "type_name" TEXT NOT NULL,
  "display_order" INTEGER NOT NULL,
  "is_ai_generated" BOOLEAN NOT NULL DEFAULT true,
  "description" TEXT
);

CREATE TABLE "public"."artefact_versions" (
  "version_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "entity_type" TEXT NOT NULL,
  "entity_id" UUID NOT NULL,
  "artefact_type_id" UUID NOT NULL,
  "version_number" INTEGER NOT NULL,
  "is_current" BOOLEAN NOT NULL DEFAULT true,
  "content_markdown" TEXT,
  "content_metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "ai_model" TEXT,
  "ai_prompt_tokens" INTEGER,
  "ai_completion_tokens" INTEGER,
  "generation_duration_ms" INTEGER,
  "contradiction_flags_json" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "additional_metadata_json" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "ai_debug_request_json" JSONB,
  "ai_debug_response_json" JSONB,
  "generated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "generated_by_user_id" UUID,
  "generated_by_email_snapshot" TEXT NOT NULL,
  "superseded_at" TIMESTAMPTZ
);

CREATE TABLE "public"."benchmark_ranges" (
  "benchmark_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID,
  "project_type" TEXT NOT NULL,
  "complexity_level" TEXT NOT NULL,
  "min_duration_days" INTEGER,
  "max_duration_days" INTEGER,
  "min_budget_gbp" NUMERIC(15,2),
  "max_budget_gbp" NUMERIC(15,2),
  "min_team_size" INTEGER,
  "max_team_size" INTEGER,
  "source" TEXT,
  "last_updated" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."budgets" (
  "budget_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "budget_category" TEXT NOT NULL,
  "budget_year" INTEGER NOT NULL,
  "planned_amount_gbp" NUMERIC(15,2) NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT
);

CREATE TABLE "public"."delivery_model_groups" (
  "delivery_model_group_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "group_code" TEXT NOT NULL,
  "group_name" TEXT NOT NULL,
  "description" TEXT,
  "display_order" INTEGER NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."delivery_model_phases" (
  "phase_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "delivery_model_id" UUID NOT NULL,
  "phase_code" TEXT NOT NULL,
  "phase_name" TEXT NOT NULL,
  "phase_order" INTEGER NOT NULL,
  "purpose" TEXT,
  "standard_outputs" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "decision_gate" TEXT,
  "gate_type" TEXT,
  "artefact_codes" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "is_optional" BOOLEAN NOT NULL DEFAULT false,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."delivery_model_quality_gates" (
  "gate_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "delivery_model_id" UUID NOT NULL,
  "deliverable" TEXT NOT NULL,
  "quality_requirement" TEXT NOT NULL,
  "reviewer_role" TEXT NOT NULL,
  "phase_code" TEXT,
  "is_mandatory" BOOLEAN NOT NULL DEFAULT true,
  "display_order" INTEGER,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."delivery_model_risk_categories" (
  "risk_category_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "delivery_model_id" UUID NOT NULL,
  "category_code" TEXT NOT NULL,
  "category_name" TEXT NOT NULL,
  "description" TEXT,
  "is_mandatory" BOOLEAN NOT NULL DEFAULT false,
  "applies_to_ai" BOOLEAN NOT NULL DEFAULT false,
  "display_order" INTEGER,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."delivery_model_roles" (
  "role_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "delivery_model_id" UUID NOT NULL,
  "role_code" TEXT NOT NULL,
  "role_name" TEXT NOT NULL,
  "responsibility" TEXT,
  "decision_rights" TEXT,
  "accountable_for" TEXT,
  "typical_phases" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "involvement_level" TEXT,
  "is_required" BOOLEAN NOT NULL DEFAULT true,
  "display_order" INTEGER,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."delivery_models" (
  "delivery_model_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "model_code" TEXT NOT NULL,
  "model_name" TEXT NOT NULL,
  "model_category" TEXT,
  "delivery_method_alignment" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "typical_use_cases" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "governance_emphasis" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "artefact_bias" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "description" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "display_order" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "delivery_model_group_id" UUID,
  "short_description" TEXT,
  "delivery_language_guidance" TEXT,
  "allows_custom_detail" BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE "public"."field_guidance" (
  "guidance_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "table_name" TEXT NOT NULL,
  "field_name" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "helper_text" TEXT,
  "placeholder" TEXT,
  "example_good" TEXT,
  "example_poor" TEXT,
  "min_length" INTEGER,
  "guidance_notes" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE "public"."generation_runs" (
  "run_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "entity_type" TEXT NOT NULL,
  "entity_id" UUID NOT NULL,
  "correlation_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "workflow_run_id" TEXT,
  "status" TEXT NOT NULL DEFAULT 'Queued'::text,
  "current_stage" TEXT,
  "stages_completed" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "is_regeneration" BOOLEAN NOT NULL DEFAULT false,
  "regenerated_stages" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "error_message" TEXT,
  "total_duration_ms" INTEGER,
  "initiated_by_user_id" UUID,
  "initiated_by_email" TEXT NOT NULL,
  "started_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "completed_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."governance_matrix" (
  "matrix_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "tier_code" TEXT NOT NULL,
  "tier_name" TEXT NOT NULL,
  "tier_level" INTEGER NOT NULL,
  "delivery_maturity" TEXT NOT NULL,
  "regulatory_intensity" TEXT NOT NULL,
  "description" TEXT,
  "required_artefacts" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "review_frequency_days" INTEGER,
  "display_order" INTEGER NOT NULL
);

CREATE TABLE "public"."governance_roles" (
  "governance_role_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "role_name" TEXT NOT NULL,
  "user_id" UUID,
  "person_name" TEXT,
  "responsibilities" TEXT,
  "decision_rights" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT
);

CREATE TABLE "public"."input_quality_assessments" (
  "assessment_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "entity_type" TEXT NOT NULL DEFAULT 'Project'::text,
  "entity_id" UUID NOT NULL,
  "run_id" UUID,
  "overall_quality" TEXT NOT NULL,
  "quality_score" INTEGER,
  "strong_fields" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "weak_fields" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "missing_fields" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "assumptions_made" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "improvements" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "risks_flagged" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "derivation_markdown" TEXT,
  "raw_assessment" JSONB,
  "assessed_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."mobile_app_sample_data" (
  "id" BIGINT NOT NULL,
  "name" TEXT,
  "email" TEXT,
  "sales" BIGINT,
  "image" TEXT
);

CREATE TABLE "public"."organisations" (
  "org_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_name" TEXT NOT NULL,
  "org_slug" TEXT NOT NULL,
  "subscription_tier" TEXT NOT NULL DEFAULT 'standard'::text,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "settings" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_acd_item_types" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_business_driver" (
  "id" INTEGER NOT NULL DEFAULT nextval('business_driver_id_seq'::regclass),
  "busines_driver" TEXT,
  "code" TEXT
);

CREATE TABLE "public"."os_complexity_levels" (
  "id" INTEGER NOT NULL DEFAULT nextval('complexity_levels_id_seq'::regclass),
  "complexity_level" TEXT,
  "helper_text" TEXT
);

CREATE TABLE "public"."os_confidence" (
  "id" INTEGER NOT NULL DEFAULT nextval('os_confidence_id_seq'::regclass),
  "confidence" TEXT
);

CREATE TABLE "public"."os_confidence_levels" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_cost_types" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_delivery_models" (
  "id" INTEGER NOT NULL DEFAULT nextval('delivery_methods_id_seq'::regclass),
  "delivery_model" TEXT
);

CREATE TABLE "public"."os_delivery_type" (
  "id" INTEGER NOT NULL DEFAULT nextval('delivery_type_id_seq'::regclass),
  "delivery_type" TEXT
);

CREATE TABLE "public"."os_fixed_or_negotiable_options" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_function" (
  "id" INTEGER NOT NULL,
  "function" TEXT,
  "code" TEXT
);

CREATE TABLE "public"."os_impact_scale" (
  "impact_score" INTEGER NOT NULL,
  "impact_label" TEXT NOT NULL,
  "description" TEXT,
  "display_order" INTEGER NOT NULL
);

CREATE TABLE "public"."os_it_systems_types" (
  "id" INTEGER NOT NULL DEFAULT nextval('os_it_systems_types_id_seq'::regclass),
  "system_type" TEXT,
  "code" TEXT
);

CREATE TABLE "public"."os_lifecycle_stage" (
  "id" INTEGER NOT NULL,
  "lifecycle_stage" TEXT NOT NULL,
  "code" TEXT NOT NULL
);

CREATE TABLE "public"."os_likelihood_scale" (
  "likelihood_score" INTEGER NOT NULL,
  "likelihood_label" TEXT NOT NULL,
  "description" TEXT,
  "display_order" INTEGER NOT NULL
);

CREATE TABLE "public"."os_option_sets" (
  "option_set_code" TEXT NOT NULL,
  "option_set_name" TEXT NOT NULL,
  "description" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_options" (
  "option_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "option_set_code" TEXT NOT NULL,
  "option_value" TEXT NOT NULL,
  "option_label" TEXT NOT NULL,
  "helper_text" TEXT,
  "display_order" INTEGER NOT NULL DEFAULT 100,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "metadata_json" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_org_familiarity" (
  "id" INTEGER NOT NULL DEFAULT nextval('os_org_familiarity_id_seq'::regclass),
  "org_familiarity" TEXT
);

CREATE TABLE "public"."os_poti_information" (
  "information_scope_id" BIGINT NOT NULL,
  "scope_code" TEXT NOT NULL,
  "scope_name" TEXT NOT NULL,
  "description" TEXT,
  "display_order" INTEGER NOT NULL DEFAULT 100,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_poti_organisation" (
  "organisation_scope_id" BIGINT NOT NULL,
  "scope_code" TEXT NOT NULL,
  "scope_name" TEXT NOT NULL,
  "description" TEXT,
  "display_order" INTEGER NOT NULL DEFAULT 100,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_poti_processes" (
  "process_scope_id" BIGINT NOT NULL,
  "scope_code" TEXT NOT NULL,
  "scope_name" TEXT NOT NULL,
  "description" TEXT,
  "display_order" INTEGER NOT NULL DEFAULT 100,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_poti_scopes_all" (
  "poti_domain" TEXT,
  "scope_code" TEXT,
  "scope_name" TEXT,
  "description" TEXT,
  "display_order" INTEGER,
  "is_active" BOOLEAN
);

CREATE TABLE "public"."os_poti_technology" (
  "technology_scope_id" BIGINT NOT NULL,
  "scope_code" TEXT NOT NULL,
  "scope_name" TEXT NOT NULL,
  "description" TEXT,
  "display_order" INTEGER NOT NULL DEFAULT 100,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_recommendation_positions" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_resourcetype" (
  "id" INTEGER NOT NULL,
  "role" TEXT
);

CREATE TABLE "public"."os_riskcategory" (
  "id" INTEGER NOT NULL,
  "category" TEXT
);

CREATE TABLE "public"."os_scale" (
  "id" INTEGER NOT NULL DEFAULT nextval('os_sclae_id_seq'::regclass),
  "scale" TEXT
);

CREATE TABLE "public"."os_scope" (
  "id" INTEGER NOT NULL,
  "scope" TEXT,
  "help_text" TEXT
);

CREATE TABLE "public"."os_scope_areas" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_scope_categories" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_scope_list_information" (
  "id" INTEGER NOT NULL DEFAULT nextval('os_scope_list_id_seq'::regclass),
  "scope_type" TEXT,
  "help_text" TEXT,
  "code" TEXT
);

CREATE TABLE "public"."os_scope_list_organisation" (
  "id" INTEGER NOT NULL DEFAULT nextval('os_scope_list_organisation_id_seq'::regclass),
  "scope_type" TEXT,
  "help_text" TEXT,
  "code" TEXT
);

CREATE TABLE "public"."os_scope_list_processes" (
  "id" INTEGER NOT NULL DEFAULT nextval('os_scope_list_processes_id_seq'::regclass),
  "scope_type" TEXT,
  "help_text" TEXT,
  "code" TEXT
);

CREATE TABLE "public"."os_scope_list_technology" (
  "id" INTEGER NOT NULL,
  "code" TEXT NOT NULL,
  "scope_type" TEXT NOT NULL DEFAULT 'Technology'::text,
  "help_text" TEXT
);

CREATE TABLE "public"."os_scope_statuses" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."os_service_industry_type" (
  "id" INTEGER NOT NULL DEFAULT nextval('service_industry_type_id_seq'::regclass),
  "service_industry_type" TEXT
);

CREATE TABLE "public"."os_source_statuses" (
  "value" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "description" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."programmes" (
  "programme_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "programme_code" TEXT NOT NULL,
  "programme_name" TEXT NOT NULL,
  "description" TEXT,
  "sponsor_user_id" UUID,
  "sro_user_id" UUID,
  "status" TEXT NOT NULL DEFAULT 'Active'::text,
  "start_date" DATE,
  "target_end_date" DATE,
  "actual_end_date" DATE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT
);

CREATE TABLE "public"."project_acd_items" (
  "acd_item_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "item_type" TEXT NOT NULL,
  "item_ref" TEXT,
  "item_description" TEXT NOT NULL,
  "owner_role" TEXT,
  "fixed_or_negotiable" TEXT,
  "converted_to_risk" BOOLEAN NOT NULL DEFAULT false,
  "linked_risk_id" UUID,
  "source_status" TEXT NOT NULL DEFAULT 'Supplied'::text,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."project_business_case_cost_lines" (
  "cost_line_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "cost_category" TEXT NOT NULL,
  "cost_description" TEXT,
  "amount" NUMERIC(14,2),
  "currency" TEXT NOT NULL DEFAULT 'GBP'::text,
  "period_year" INTEGER,
  "timing" TEXT,
  "cost_type" TEXT,
  "confidence" TEXT NOT NULL DEFAULT 'Indicative'::text,
  "source_status" TEXT NOT NULL DEFAULT 'Supplied'::text,
  "notes" TEXT,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."project_business_case_options" (
  "option_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "option_code" TEXT,
  "option_name" TEXT NOT NULL,
  "option_description" TEXT,
  "is_recommended" BOOLEAN NOT NULL DEFAULT false,
  "recommendation_position" TEXT,
  "cost_level" TEXT,
  "schedule_impact" TEXT,
  "risk_level" TEXT,
  "delivery_complexity" TEXT,
  "strategic_alignment" TEXT,
  "benefit_speed" TEXT,
  "sustainability" TEXT,
  "benefits" ARRAY,
  "disadvantages" ARRAY,
  "source_status" TEXT NOT NULL DEFAULT 'Supplied'::text,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."project_context" (
  "context_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "business_problem" TEXT,
  "strategic_objectives" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "success_criteria" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "constraints" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "assumptions" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "key_stakeholders" JSONB NOT NULL DEFAULT '[]'::jsonb,
  "affected_departments" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "systems_impacted" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "integration_requirements" ARRAY NOT NULL DEFAULT ARRAY[]::text[],
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT,
  "scope_poti" ARRAY,
  "scope_processes" ARRAY,
  "scope_organisation" ARRAY,
  "scope_information" ARRAY,
  "scope_technology" ARRAY,
  "it_system_types" ARRAY,
  "delivery_model_id" UUID,
  "delivery_model_other" TEXT,
  "delivery_model_rationale" TEXT,
  "delivery_model_group_id" UUID,
  "delivery_model_custom" TEXT,
  "recommended_option_name" TEXT,
  "recommended_option_rationale" TEXT,
  "decision_ask" TEXT,
  "approval_ask" TEXT,
  "funding_or_resource_ask" TEXT,
  "next_stage" TEXT,
  "delivery_tailoring_rationale" TEXT,
  "content_fidelity_notes" TEXT,
  "explicit_out_of_scope" TEXT,
  "known_dependencies" TEXT,
  "key_assumptions" TEXT,
  "key_constraints" TEXT,
  "resource_model" TEXT,
  "key_roles_required" ARRAY,
  "stakeholder_groups" ARRAY,
  "budget_confidence" TEXT,
  "budget_notes" TEXT,
  "quality_assurance_expectations" TEXT
);

CREATE TABLE "public"."project_contradictions" (
  "contradiction_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "contradiction_type" TEXT NOT NULL,
  "field_name" TEXT NOT NULL,
  "expected_min" NUMERIC(15,2),
  "expected_max" NUMERIC(15,2),
  "actual_value" NUMERIC(15,2),
  "expected_range_source" TEXT,
  "rationale" TEXT NOT NULL,
  "severity" TEXT NOT NULL DEFAULT 'Medium'::text,
  "status" TEXT NOT NULL DEFAULT 'Open'::text,
  "detected_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "detected_by_user_id" UUID,
  "resolved_at" TIMESTAMPTZ,
  "resolved_by_user_id" UUID,
  "resolution_notes" TEXT
);

CREATE TABLE "public"."project_delivery_models" (
  "project_delivery_model_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "delivery_model_id" UUID NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'Primary'::text,
  "rationale" TEXT,
  "display_order" INTEGER NOT NULL DEFAULT 10,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."project_scope_items" (
  "scope_item_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "scope_status" TEXT NOT NULL,
  "scope_area" TEXT NOT NULL,
  "scope_category" TEXT,
  "scope_item" TEXT NOT NULL,
  "notes" TEXT,
  "source_status" TEXT NOT NULL DEFAULT 'Supplied'::text,
  "sort_order" INTEGER NOT NULL DEFAULT 1,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE "public"."projects" (
  "project_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "programme_id" UUID,
  "project_code" TEXT NOT NULL,
  "project_name" TEXT NOT NULL,
  "description" TEXT,
  "delivery_maturity" TEXT NOT NULL,
  "regulatory_intensity" TEXT NOT NULL,
  "governance_tier_id" UUID,
  "pipeline_stage" TEXT NOT NULL DEFAULT 'Not Started'::text,
  "context_generated_at" TIMESTAMPTZ,
  "charter_generated_at" TIMESTAMPTZ,
  "plan_generated_at" TIMESTAMPTZ,
  "resources_generated_at" TIMESTAMPTZ,
  "risks_generated_at" TIMESTAMPTZ,
  "financials_generated_at" TIMESTAMPTZ,
  "current_context_version_id" UUID,
  "current_charter_version_id" UUID,
  "current_plan_version_id" UUID,
  "current_resources_version_id" UUID,
  "current_risks_version_id" UUID,
  "current_financials_version_id" UUID,
  "sponsor_user_id" UUID,
  "pm_user_id" UUID,
  "status" TEXT NOT NULL DEFAULT 'Initiation'::text,
  "start_date" DATE,
  "target_end_date" DATE,
  "actual_end_date" DATE,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT,
  "business_drivers" ARRAY DEFAULT '{}'::text[],
  "impacted_functions" ARRAY DEFAULT '{}'::text[],
  "experience_level" TEXT,
  "scale" TEXT,
  "complexity" TEXT,
  "entity_type" TEXT,
  "delivery_method" TEXT,
  "lifecycle_stage" TEXT,
  "confidence_level" TEXT,
  "estimated_budget_gbp" NUMERIC(10,0),
  "service_industry" TEXT
);

CREATE TABLE "public"."rag_thresholds" (
  "threshold_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID,
  "green_max" INTEGER NOT NULL DEFAULT 5,
  "amber_max" INTEGER NOT NULL DEFAULT 14,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT NOT NULL
);

CREATE TABLE "public"."risks" (
  "risk_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "risk_code" TEXT NOT NULL,
  "risk_title" TEXT NOT NULL,
  "risk_description" TEXT,
  "risk_category" TEXT,
  "risk_source_type" TEXT NOT NULL,
  "likelihood_score" INTEGER NOT NULL,
  "impact_score" INTEGER NOT NULL,
  "risk_score" INTEGER,
  "mitigation_strategy" TEXT,
  "mitigation_owner_user_id" UUID,
  "status" TEXT NOT NULL DEFAULT 'Open'::text,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT
);

CREATE TABLE "public"."risks_with_rag" (
  "risk_id" UUID,
  "org_id" UUID,
  "project_id" UUID,
  "risk_code" TEXT,
  "risk_title" TEXT,
  "risk_description" TEXT,
  "risk_category" TEXT,
  "risk_source_type" TEXT,
  "likelihood_score" INTEGER,
  "impact_score" INTEGER,
  "risk_score" INTEGER,
  "mitigation_strategy" TEXT,
  "mitigation_owner_user_id" UUID,
  "status" TEXT,
  "created_at" TIMESTAMPTZ,
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ,
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT,
  "rag_status" TEXT
);

CREATE TABLE "public"."stakeholders" (
  "stakeholder_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "stakeholder_name" TEXT NOT NULL,
  "role_title" TEXT,
  "stakeholder_type" TEXT NOT NULL,
  "department" TEXT,
  "impact" TEXT,
  "contact_email" TEXT,
  "contact_phone" TEXT,
  "notes" TEXT,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT
);

CREATE TABLE "public"."task_dependencies" (
  "dependency_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "predecessor_task_id" UUID NOT NULL,
  "successor_task_id" UUID NOT NULL,
  "dependency_type" TEXT NOT NULL DEFAULT 'FS'::text,
  "lag_days" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID
);

CREATE TABLE "public"."tasks" (
  "task_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "tranche_id" UUID,
  "parent_task_id" UUID,
  "task_name" TEXT NOT NULL,
  "description" TEXT,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "effort_days" NUMERIC(10,2),
  "progress_percentage" INTEGER NOT NULL DEFAULT 0,
  "assigned_to_user_id" UUID,
  "status" TEXT NOT NULL DEFAULT 'Not Started'::text,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT
);

CREATE TABLE "public"."tranches" (
  "tranche_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "org_id" UUID NOT NULL,
  "project_id" UUID NOT NULL,
  "tranche_name" TEXT NOT NULL,
  "description" TEXT,
  "start_date" DATE NOT NULL,
  "end_date" DATE NOT NULL,
  "order_index" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "created_by_user_id" UUID,
  "created_by_email_snapshot" TEXT,
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "updated_by_user_id" UUID,
  "updated_by_email_snapshot" TEXT
);

CREATE TABLE "public"."user_org_roles" (
  "user_org_role_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "user_id" UUID NOT NULL,
  "org_id" UUID NOT NULL,
  "role" TEXT NOT NULL,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "assigned_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "assigned_by_user_id" UUID,
  "assigned_by_email_snapshot" TEXT
);

CREATE TABLE "public"."users" (
  "user_id" UUID NOT NULL DEFAULT gen_random_uuid(),
  "email" TEXT NOT NULL,
  "full_name" TEXT,
  "is_active" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "last_login_at" TIMESTAMPTZ
);


-- =============================================================================
-- SECTION 2: Primary keys
-- =============================================================================

ALTER TABLE "public"."activity_log" ADD CONSTRAINT "activity_log_pkey" PRIMARY KEY ("log_id");
ALTER TABLE "public"."actuals" ADD CONSTRAINT "actuals_pkey" PRIMARY KEY ("actual_id");
ALTER TABLE "public"."artefact_types" ADD CONSTRAINT "artefact_types_pkey" PRIMARY KEY ("artefact_type_id");
ALTER TABLE "public"."artefact_versions" ADD CONSTRAINT "artefact_versions_pkey" PRIMARY KEY ("version_id");
ALTER TABLE "public"."benchmark_ranges" ADD CONSTRAINT "benchmark_ranges_pkey" PRIMARY KEY ("benchmark_id");
ALTER TABLE "public"."budgets" ADD CONSTRAINT "budgets_pkey" PRIMARY KEY ("budget_id");
ALTER TABLE "public"."delivery_model_groups" ADD CONSTRAINT "delivery_model_groups_pkey" PRIMARY KEY ("delivery_model_group_id");
ALTER TABLE "public"."delivery_model_phases" ADD CONSTRAINT "delivery_model_phases_pkey" PRIMARY KEY ("phase_id");
ALTER TABLE "public"."delivery_model_quality_gates" ADD CONSTRAINT "delivery_model_quality_gates_pkey" PRIMARY KEY ("gate_id");
ALTER TABLE "public"."delivery_model_risk_categories" ADD CONSTRAINT "delivery_model_risk_categories_pkey" PRIMARY KEY ("risk_category_id");
ALTER TABLE "public"."delivery_model_roles" ADD CONSTRAINT "delivery_model_roles_pkey" PRIMARY KEY ("role_id");
ALTER TABLE "public"."delivery_models" ADD CONSTRAINT "delivery_models_pkey" PRIMARY KEY ("delivery_model_id");
ALTER TABLE "public"."field_guidance" ADD CONSTRAINT "field_guidance_pkey" PRIMARY KEY ("guidance_id");
ALTER TABLE "public"."generation_runs" ADD CONSTRAINT "generation_runs_pkey" PRIMARY KEY ("run_id");
ALTER TABLE "public"."governance_matrix" ADD CONSTRAINT "governance_matrix_pkey" PRIMARY KEY ("matrix_id");
ALTER TABLE "public"."governance_roles" ADD CONSTRAINT "governance_roles_pkey" PRIMARY KEY ("governance_role_id");
ALTER TABLE "public"."input_quality_assessments" ADD CONSTRAINT "input_quality_assessments_pkey" PRIMARY KEY ("assessment_id");
ALTER TABLE "public"."mobile_app_sample_data" ADD CONSTRAINT "mobile_app_sample_data_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."organisations" ADD CONSTRAINT "organisations_pkey" PRIMARY KEY ("org_id");
ALTER TABLE "public"."os_acd_item_types" ADD CONSTRAINT "os_acd_item_types_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_business_driver" ADD CONSTRAINT "business_driver_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_complexity_levels" ADD CONSTRAINT "complexity_levels_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_confidence" ADD CONSTRAINT "os_confidence_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_confidence_levels" ADD CONSTRAINT "os_confidence_levels_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_cost_types" ADD CONSTRAINT "os_cost_types_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_delivery_models" ADD CONSTRAINT "delivery_methods_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_delivery_type" ADD CONSTRAINT "delivery_type_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_fixed_or_negotiable_options" ADD CONSTRAINT "os_fixed_or_negotiable_options_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_function" ADD CONSTRAINT "os_function_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_impact_scale" ADD CONSTRAINT "impact_scale_pkey" PRIMARY KEY ("impact_score");
ALTER TABLE "public"."os_it_systems_types" ADD CONSTRAINT "os_it_systems_types_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_lifecycle_stage" ADD CONSTRAINT "os_lifecycle_stage_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_likelihood_scale" ADD CONSTRAINT "likelihood_scale_pkey" PRIMARY KEY ("likelihood_score");
ALTER TABLE "public"."os_option_sets" ADD CONSTRAINT "os_option_sets_pkey" PRIMARY KEY ("option_set_code");
ALTER TABLE "public"."os_options" ADD CONSTRAINT "os_options_pkey" PRIMARY KEY ("option_id");
ALTER TABLE "public"."os_org_familiarity" ADD CONSTRAINT "os_org_familiarity_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_poti_information" ADD CONSTRAINT "os_poti_information_pkey" PRIMARY KEY ("information_scope_id");
ALTER TABLE "public"."os_poti_organisation" ADD CONSTRAINT "os_poti_organisation_pkey" PRIMARY KEY ("organisation_scope_id");
ALTER TABLE "public"."os_poti_processes" ADD CONSTRAINT "os_poti_processes_pkey" PRIMARY KEY ("process_scope_id");
ALTER TABLE "public"."os_poti_technology" ADD CONSTRAINT "os_poti_technology_pkey" PRIMARY KEY ("technology_scope_id");
ALTER TABLE "public"."os_recommendation_positions" ADD CONSTRAINT "os_recommendation_positions_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_resourcetype" ADD CONSTRAINT "os_resourcetype_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_riskcategory" ADD CONSTRAINT "osriskcategory_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_scale" ADD CONSTRAINT "os_sclae_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_scope" ADD CONSTRAINT "os_scope_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_scope_areas" ADD CONSTRAINT "os_scope_areas_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_scope_categories" ADD CONSTRAINT "os_scope_categories_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_scope_list_information" ADD CONSTRAINT "os_scope_list_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_scope_list_organisation" ADD CONSTRAINT "os_scope_list_organisation_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_scope_list_processes" ADD CONSTRAINT "os_scope_list_processes_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_scope_list_technology" ADD CONSTRAINT "os_scope_list_technology_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_scope_statuses" ADD CONSTRAINT "os_scope_statuses_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."os_service_industry_type" ADD CONSTRAINT "service_industry_type_pkey" PRIMARY KEY ("id");
ALTER TABLE "public"."os_source_statuses" ADD CONSTRAINT "os_source_statuses_pkey" PRIMARY KEY ("value");
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_pkey" PRIMARY KEY ("programme_id");
ALTER TABLE "public"."project_acd_items" ADD CONSTRAINT "project_acd_items_pkey" PRIMARY KEY ("acd_item_id");
ALTER TABLE "public"."project_business_case_cost_lines" ADD CONSTRAINT "project_business_case_cost_lines_pkey" PRIMARY KEY ("cost_line_id");
ALTER TABLE "public"."project_business_case_options" ADD CONSTRAINT "project_business_case_options_pkey" PRIMARY KEY ("option_id");
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_pkey" PRIMARY KEY ("context_id");
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_pkey" PRIMARY KEY ("contradiction_id");
ALTER TABLE "public"."project_delivery_models" ADD CONSTRAINT "project_delivery_models_pkey" PRIMARY KEY ("project_delivery_model_id");
ALTER TABLE "public"."project_scope_items" ADD CONSTRAINT "project_scope_items_pkey" PRIMARY KEY ("scope_item_id");
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_pkey" PRIMARY KEY ("project_id");
ALTER TABLE "public"."rag_thresholds" ADD CONSTRAINT "rag_thresholds_pkey" PRIMARY KEY ("threshold_id");
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_pkey" PRIMARY KEY ("risk_id");
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_pkey" PRIMARY KEY ("stakeholder_id");
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "task_dependencies_pkey" PRIMARY KEY ("dependency_id");
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_pkey" PRIMARY KEY ("task_id");
ALTER TABLE "public"."tranches" ADD CONSTRAINT "tranches_pkey" PRIMARY KEY ("tranche_id");
ALTER TABLE "public"."user_org_roles" ADD CONSTRAINT "user_org_roles_pkey" PRIMARY KEY ("user_org_role_id");
ALTER TABLE "public"."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("user_id");


-- =============================================================================
-- SECTION 3: Unique constraints
-- =============================================================================

ALTER TABLE "public"."artefact_types" ADD CONSTRAINT "artefact_types_type_code_key" UNIQUE ("type_code");
ALTER TABLE "public"."artefact_versions" ADD CONSTRAINT "artefact_versions_entity_type_entity_id_artefact_type_id_ve_key" UNIQUE ("entity_type", "entity_id", "artefact_type_id", "version_number");
ALTER TABLE "public"."budgets" ADD CONSTRAINT "budgets_org_id_project_id_budget_category_budget_year_key" UNIQUE ("org_id", "project_id", "budget_category", "budget_year");
ALTER TABLE "public"."delivery_model_groups" ADD CONSTRAINT "delivery_model_groups_group_code_key" UNIQUE ("group_code");
ALTER TABLE "public"."delivery_model_phases" ADD CONSTRAINT "delivery_model_phases_delivery_model_id_phase_code_key" UNIQUE ("delivery_model_id", "phase_code");
ALTER TABLE "public"."delivery_model_phases" ADD CONSTRAINT "delivery_model_phases_delivery_model_id_phase_order_key" UNIQUE ("delivery_model_id", "phase_order");
ALTER TABLE "public"."delivery_model_risk_categories" ADD CONSTRAINT "delivery_model_risk_categorie_delivery_model_id_category_co_key" UNIQUE ("delivery_model_id", "category_code");
ALTER TABLE "public"."delivery_model_roles" ADD CONSTRAINT "delivery_model_roles_delivery_model_id_role_code_key" UNIQUE ("delivery_model_id", "role_code");
ALTER TABLE "public"."delivery_models" ADD CONSTRAINT "delivery_models_model_code_key" UNIQUE ("model_code");
ALTER TABLE "public"."field_guidance" ADD CONSTRAINT "field_guidance_table_name_field_name_key" UNIQUE ("table_name", "field_name");
ALTER TABLE "public"."generation_runs" ADD CONSTRAINT "generation_runs_correlation_id_key" UNIQUE ("correlation_id");
ALTER TABLE "public"."governance_matrix" ADD CONSTRAINT "governance_matrix_delivery_maturity_regulatory_intensity_key" UNIQUE ("delivery_maturity", "regulatory_intensity");
ALTER TABLE "public"."governance_roles" ADD CONSTRAINT "governance_roles_org_id_project_id_role_name_key" UNIQUE ("org_id", "project_id", "role_name");
ALTER TABLE "public"."organisations" ADD CONSTRAINT "organisations_org_slug_key" UNIQUE ("org_slug");
ALTER TABLE "public"."os_lifecycle_stage" ADD CONSTRAINT "os_lifecycle_stage_code_key" UNIQUE ("code");
ALTER TABLE "public"."os_options" ADD CONSTRAINT "os_options_option_set_code_option_value_key" UNIQUE ("option_set_code", "option_value");
ALTER TABLE "public"."os_poti_information" ADD CONSTRAINT "os_poti_information_scope_code_key" UNIQUE ("scope_code");
ALTER TABLE "public"."os_poti_organisation" ADD CONSTRAINT "os_poti_organisation_scope_code_key" UNIQUE ("scope_code");
ALTER TABLE "public"."os_poti_processes" ADD CONSTRAINT "os_poti_processes_scope_code_key" UNIQUE ("scope_code");
ALTER TABLE "public"."os_poti_technology" ADD CONSTRAINT "os_poti_technology_scope_code_key" UNIQUE ("scope_code");
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_org_id_programme_code_key" UNIQUE ("org_id", "programme_code");
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_project_id_key" UNIQUE ("project_id");
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_org_id_project_code_key" UNIQUE ("org_id", "project_code");
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_org_id_project_id_risk_code_key" UNIQUE ("org_id", "project_id", "risk_code");
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "task_dependencies_predecessor_task_id_successor_task_id_key" UNIQUE ("predecessor_task_id", "successor_task_id");
ALTER TABLE "public"."tranches" ADD CONSTRAINT "tranches_org_id_project_id_order_index_key" UNIQUE ("org_id", "project_id", "order_index");
ALTER TABLE "public"."user_org_roles" ADD CONSTRAINT "user_org_roles_user_id_org_id_key" UNIQUE ("user_id", "org_id");
ALTER TABLE "public"."users" ADD CONSTRAINT "users_email_key" UNIQUE ("email");


-- =============================================================================
-- SECTION 4: Foreign keys
-- =============================================================================

ALTER TABLE "public"."activity_log" ADD CONSTRAINT "activity_log_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."activity_log" ADD CONSTRAINT "activity_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "public"."actuals" ADD CONSTRAINT "actuals_budget_id_fkey" FOREIGN KEY ("budget_id") REFERENCES "public"."budgets" ("budget_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."actuals" ADD CONSTRAINT "actuals_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."actuals" ADD CONSTRAINT "actuals_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."actuals" ADD CONSTRAINT "actuals_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."artefact_versions" ADD CONSTRAINT "artefact_versions_artefact_type_id_fkey" FOREIGN KEY ("artefact_type_id") REFERENCES "public"."artefact_types" ("artefact_type_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."artefact_versions" ADD CONSTRAINT "artefact_versions_generated_by_user_id_fkey" FOREIGN KEY ("generated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."artefact_versions" ADD CONSTRAINT "artefact_versions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."benchmark_ranges" ADD CONSTRAINT "benchmark_ranges_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."budgets" ADD CONSTRAINT "budgets_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."budgets" ADD CONSTRAINT "budgets_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."budgets" ADD CONSTRAINT "budgets_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."budgets" ADD CONSTRAINT "budgets_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."delivery_model_phases" ADD CONSTRAINT "delivery_model_phases_delivery_model_id_fkey" FOREIGN KEY ("delivery_model_id") REFERENCES "public"."delivery_models" ("delivery_model_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."delivery_model_quality_gates" ADD CONSTRAINT "delivery_model_quality_gates_delivery_model_id_fkey" FOREIGN KEY ("delivery_model_id") REFERENCES "public"."delivery_models" ("delivery_model_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."delivery_model_risk_categories" ADD CONSTRAINT "delivery_model_risk_categories_delivery_model_id_fkey" FOREIGN KEY ("delivery_model_id") REFERENCES "public"."delivery_models" ("delivery_model_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."delivery_model_roles" ADD CONSTRAINT "delivery_model_roles_delivery_model_id_fkey" FOREIGN KEY ("delivery_model_id") REFERENCES "public"."delivery_models" ("delivery_model_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."delivery_models" ADD CONSTRAINT "delivery_models_delivery_model_group_id_fkey" FOREIGN KEY ("delivery_model_group_id") REFERENCES "public"."delivery_model_groups" ("delivery_model_group_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."generation_runs" ADD CONSTRAINT "generation_runs_initiated_by_user_id_fkey" FOREIGN KEY ("initiated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."generation_runs" ADD CONSTRAINT "generation_runs_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."governance_roles" ADD CONSTRAINT "governance_roles_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."governance_roles" ADD CONSTRAINT "governance_roles_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."governance_roles" ADD CONSTRAINT "governance_roles_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."governance_roles" ADD CONSTRAINT "governance_roles_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."governance_roles" ADD CONSTRAINT "governance_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "public"."input_quality_assessments" ADD CONSTRAINT "input_quality_assessments_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."input_quality_assessments" ADD CONSTRAINT "input_quality_assessments_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "public"."generation_runs" ("run_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."os_options" ADD CONSTRAINT "os_options_option_set_code_fkey" FOREIGN KEY ("option_set_code") REFERENCES "public"."os_option_sets" ("option_set_code") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_sponsor_user_id_fkey" FOREIGN KEY ("sponsor_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_sro_user_id_fkey" FOREIGN KEY ("sro_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_acd_items" ADD CONSTRAINT "project_acd_items_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_acd_items" ADD CONSTRAINT "project_acd_items_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_business_case_cost_lines" ADD CONSTRAINT "project_business_case_cost_lines_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_business_case_cost_lines" ADD CONSTRAINT "project_business_case_cost_lines_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_business_case_options" ADD CONSTRAINT "project_business_case_options_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_business_case_options" ADD CONSTRAINT "project_business_case_options_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_delivery_model_group_id_fkey" FOREIGN KEY ("delivery_model_group_id") REFERENCES "public"."delivery_model_groups" ("delivery_model_group_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_delivery_model_id_fkey" FOREIGN KEY ("delivery_model_id") REFERENCES "public"."delivery_models" ("delivery_model_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."project_context" ADD CONSTRAINT "project_context_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_detected_by_user_id_fkey" FOREIGN KEY ("detected_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_resolved_by_user_id_fkey" FOREIGN KEY ("resolved_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_delivery_models" ADD CONSTRAINT "project_delivery_models_delivery_model_id_fkey" FOREIGN KEY ("delivery_model_id") REFERENCES "public"."delivery_models" ("delivery_model_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_delivery_models" ADD CONSTRAINT "project_delivery_models_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."project_scope_items" ADD CONSTRAINT "project_scope_items_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."project_scope_items" ADD CONSTRAINT "project_scope_items_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_governance_tier_id_fkey" FOREIGN KEY ("governance_tier_id") REFERENCES "public"."governance_matrix" ("matrix_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_pm_user_id_fkey" FOREIGN KEY ("pm_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_programme_id_fkey" FOREIGN KEY ("programme_id") REFERENCES "public"."programmes" ("programme_id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_sponsor_user_id_fkey" FOREIGN KEY ("sponsor_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."rag_thresholds" ADD CONSTRAINT "rag_thresholds_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."rag_thresholds" ADD CONSTRAINT "rag_thresholds_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_impact_score_fkey" FOREIGN KEY ("impact_score") REFERENCES "public"."os_impact_scale" ("impact_score") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_likelihood_score_fkey" FOREIGN KEY ("likelihood_score") REFERENCES "public"."os_likelihood_scale" ("likelihood_score") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_mitigation_owner_user_id_fkey" FOREIGN KEY ("mitigation_owner_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "task_dependencies_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "task_dependencies_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "task_dependencies_predecessor_task_id_fkey" FOREIGN KEY ("predecessor_task_id") REFERENCES "public"."tasks" ("task_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "task_dependencies_successor_task_id_fkey" FOREIGN KEY ("successor_task_id") REFERENCES "public"."tasks" ("task_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_assigned_to_user_id_fkey" FOREIGN KEY ("assigned_to_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_parent_task_id_fkey" FOREIGN KEY ("parent_task_id") REFERENCES "public"."tasks" ("task_id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_tranche_id_fkey" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranches" ("tranche_id") ON UPDATE NO ACTION ON DELETE SET NULL;
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."tranches" ADD CONSTRAINT "tranches_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."tranches" ADD CONSTRAINT "tranches_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."tranches" ADD CONSTRAINT "tranches_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects" ("project_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."tranches" ADD CONSTRAINT "tranches_updated_by_user_id_fkey" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."user_org_roles" ADD CONSTRAINT "user_org_roles_assigned_by_user_id_fkey" FOREIGN KEY ("assigned_by_user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."user_org_roles" ADD CONSTRAINT "user_org_roles_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "public"."organisations" ("org_id") ON UPDATE NO ACTION ON DELETE CASCADE;
ALTER TABLE "public"."user_org_roles" ADD CONSTRAINT "user_org_roles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("user_id") ON UPDATE NO ACTION ON DELETE CASCADE;


-- =============================================================================
-- SECTION 5: Check constraints
-- =============================================================================

ALTER TABLE "public"."activity_log" ADD CONSTRAINT "activity_log_action_check" CHECK ((action = ANY (ARRAY['Created'::text, 'Updated'::text, 'Deleted'::text, 'Generated'::text, 'Approved'::text, 'Rejected'::text])));
ALTER TABLE "public"."artefact_versions" ADD CONSTRAINT "artefact_versions_entity_type_check" CHECK ((entity_type = ANY (ARRAY['Project'::text, 'Programme'::text])));
ALTER TABLE "public"."artefact_versions" ADD CONSTRAINT "artefact_versions_version_number_check" CHECK ((version_number > 0));
ALTER TABLE "public"."benchmark_ranges" ADD CONSTRAINT "benchmark_ranges_complexity_level_check" CHECK ((complexity_level = ANY (ARRAY['Simple'::text, 'Contained'::text, 'High-impact'::text, 'Enterprise-wide'::text])));
ALTER TABLE "public"."benchmark_ranges" ADD CONSTRAINT "valid_budget" CHECK (((min_budget_gbp IS NULL) OR (max_budget_gbp IS NULL) OR (min_budget_gbp <= max_budget_gbp)));
ALTER TABLE "public"."benchmark_ranges" ADD CONSTRAINT "valid_duration" CHECK (((min_duration_days IS NULL) OR (max_duration_days IS NULL) OR (min_duration_days <= max_duration_days)));
ALTER TABLE "public"."benchmark_ranges" ADD CONSTRAINT "valid_team_size" CHECK (((min_team_size IS NULL) OR (max_team_size IS NULL) OR (min_team_size <= max_team_size)));
ALTER TABLE "public"."budgets" ADD CONSTRAINT "budgets_budget_category_check" CHECK ((budget_category = ANY (ARRAY['Labour'::text, 'Software'::text, 'Hardware'::text, 'Consultancy'::text, 'Contingency'::text, 'Other'::text])));
ALTER TABLE "public"."budgets" ADD CONSTRAINT "positive_budget" CHECK ((planned_amount_gbp >= (0)::numeric));
ALTER TABLE "public"."delivery_model_phases" ADD CONSTRAINT "delivery_model_phases_gate_type_check" CHECK ((gate_type = ANY (ARRAY['approval'::text, 'review'::text, 'readiness'::text, 'information'::text])));
ALTER TABLE "public"."delivery_model_roles" ADD CONSTRAINT "delivery_model_roles_involvement_level_check" CHECK ((involvement_level = ANY (ARRAY['Lead'::text, 'Core'::text, 'Support'::text, 'Consulted'::text, 'Informed'::text])));
ALTER TABLE "public"."delivery_models" ADD CONSTRAINT "delivery_models_model_category_check" CHECK ((model_category = ANY (ARRAY['Project'::text, 'Programme'::text, 'Portfolio'::text, 'Agile'::text, 'Scaled Agile'::text, 'Service Management'::text, 'Governance'::text, 'Engineering'::text, 'Standard'::text, 'Custom'::text])));
ALTER TABLE "public"."generation_runs" ADD CONSTRAINT "generation_runs_entity_type_check" CHECK ((entity_type = ANY (ARRAY['Project'::text, 'Programme'::text])));
ALTER TABLE "public"."generation_runs" ADD CONSTRAINT "generation_runs_status_check" CHECK ((status = ANY (ARRAY['Queued'::text, 'Running'::text, 'Completed'::text, 'Failed'::text, 'Cancelled'::text])));
ALTER TABLE "public"."governance_matrix" ADD CONSTRAINT "governance_matrix_delivery_maturity_check" CHECK ((delivery_maturity = ANY (ARRAY['Low'::text, 'Emerging'::text, 'Moderate'::text, 'High'::text, 'Optimised'::text])));
ALTER TABLE "public"."governance_matrix" ADD CONSTRAINT "governance_matrix_regulatory_intensity_check" CHECK ((regulatory_intensity = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text, 'Severe'::text])));
ALTER TABLE "public"."governance_matrix" ADD CONSTRAINT "governance_matrix_tier_level_check" CHECK (((tier_level >= 1) AND (tier_level <= 4)));
ALTER TABLE "public"."governance_matrix" ADD CONSTRAINT "governance_matrix_tier_name_check" CHECK ((tier_name = ANY (ARRAY['Light'::text, 'Standard'::text, 'Enhanced'::text, 'Rigorous'::text])));
ALTER TABLE "public"."input_quality_assessments" ADD CONSTRAINT "input_quality_assessments_overall_quality_check" CHECK ((overall_quality = ANY (ARRAY['Strong'::text, 'Adequate'::text, 'Sparse'::text, 'Inconsistent'::text])));
ALTER TABLE "public"."input_quality_assessments" ADD CONSTRAINT "input_quality_assessments_quality_score_check" CHECK (((quality_score >= 0) AND (quality_score <= 100)));
ALTER TABLE "public"."organisations" ADD CONSTRAINT "org_slug_format" CHECK ((org_slug ~ '^[a-z0-9-]+$'::text));
ALTER TABLE "public"."os_impact_scale" ADD CONSTRAINT "impact_scale_impact_score_check" CHECK (((impact_score >= 1) AND (impact_score <= 5)));
ALTER TABLE "public"."os_likelihood_scale" ADD CONSTRAINT "likelihood_scale_likelihood_score_check" CHECK (((likelihood_score >= 1) AND (likelihood_score <= 5)));
ALTER TABLE "public"."programmes" ADD CONSTRAINT "programmes_status_check" CHECK ((status = ANY (ARRAY['Active'::text, 'On Hold'::text, 'Closed'::text])));
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_contradiction_type_check" CHECK ((contradiction_type = ANY (ARRAY['Duration vs Complexity'::text, 'Budget vs Scope'::text, 'Team Size vs Deliverables'::text, 'Risk Profile vs Governance'::text, 'Other'::text])));
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_severity_check" CHECK ((severity = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text])));
ALTER TABLE "public"."project_contradictions" ADD CONSTRAINT "project_contradictions_status_check" CHECK ((status = ANY (ARRAY['Open'::text, 'Acknowledged'::text, 'Resolved'::text, 'Ignored'::text])));
ALTER TABLE "public"."project_delivery_models" ADD CONSTRAINT "project_delivery_models_role_check" CHECK ((role = ANY (ARRAY['Primary'::text, 'Secondary'::text, 'Influencing'::text])));
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_delivery_maturity_check" CHECK ((delivery_maturity = ANY (ARRAY['Low'::text, 'Emerging'::text, 'Moderate'::text, 'High'::text, 'Optimised'::text])));
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_pipeline_stage_check" CHECK ((pipeline_stage = ANY (ARRAY['Not Started'::text, 'Context'::text, 'Charter'::text, 'Plan'::text, 'Resources'::text, 'Risks'::text, 'Financials'::text, 'Complete'::text])));
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_regulatory_intensity_check" CHECK ((regulatory_intensity = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text, 'Severe'::text])));
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_status_check" CHECK ((status = ANY (ARRAY['Initiation'::text, 'Planning'::text, 'Execution'::text, 'Closure'::text, 'Cancelled'::text])));
ALTER TABLE "public"."rag_thresholds" ADD CONSTRAINT "valid_thresholds" CHECK ((green_max < amber_max));
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_risk_category_check" CHECK ((risk_category = ANY (ARRAY['Technical'::text, 'Commercial'::text, 'Resource'::text, 'Schedule'::text, 'Stakeholder'::text, 'Other'::text])));
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_risk_source_type_check" CHECK ((risk_source_type = ANY (ARRAY['Explicit'::text, 'Derived_Assumption'::text, 'Derived_Dependency'::text, 'Derived_Constraint'::text])));
ALTER TABLE "public"."risks" ADD CONSTRAINT "risks_status_check" CHECK ((status = ANY (ARRAY['Open'::text, 'Mitigated'::text, 'Accepted'::text, 'Closed'::text])));
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_impact_check" CHECK ((impact = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text])));
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_influence_check" CHECK ((department = ANY (ARRAY['Low'::text, 'Medium'::text, 'High'::text])));
ALTER TABLE "public"."stakeholders" ADD CONSTRAINT "stakeholders_stakeholder_type_check" CHECK ((stakeholder_type = ANY (ARRAY['Sponsor'::text, 'SRO'::text, 'Board'::text, 'BCM'::text, 'SME'::text, 'Vendor'::text, 'End User'::text, 'Other'::text])));
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "no_self_dependency" CHECK ((predecessor_task_id <> successor_task_id));
ALTER TABLE "public"."task_dependencies" ADD CONSTRAINT "task_dependencies_dependency_type_check" CHECK ((dependency_type = ANY (ARRAY['FS'::text, 'SS'::text, 'FF'::text, 'SF'::text])));
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_progress_percentage_check" CHECK (((progress_percentage >= 0) AND (progress_percentage <= 100)));
ALTER TABLE "public"."tasks" ADD CONSTRAINT "tasks_status_check" CHECK ((status = ANY (ARRAY['Not Started'::text, 'In Progress'::text, 'Completed'::text, 'Blocked'::text, 'Cancelled'::text])));
ALTER TABLE "public"."tasks" ADD CONSTRAINT "valid_task_dates" CHECK ((end_date >= start_date));
ALTER TABLE "public"."tranches" ADD CONSTRAINT "valid_tranche_dates" CHECK ((end_date >= start_date));
ALTER TABLE "public"."user_org_roles" ADD CONSTRAINT "user_org_roles_role_check" CHECK ((role = ANY (ARRAY['Owner'::text, 'Admin'::text, 'PM'::text, 'Contributor'::text, 'Viewer'::text, 'Auditor'::text])));
ALTER TABLE "public"."users" ADD CONSTRAINT "email_format" CHECK ((email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text));


-- =============================================================================
-- SECTION 6: Indexes (excluding PK/UQ-implicit indexes)
-- =============================================================================

CREATE INDEX idx_actuals_org_project ON public.actuals USING btree (org_id, project_id);
CREATE INDEX idx_artefact_versions_current ON public.artefact_versions USING btree (entity_type, entity_id, artefact_type_id) WHERE (is_current = true);
CREATE INDEX idx_artefact_versions_entity ON public.artefact_versions USING btree (entity_type, entity_id);
CREATE INDEX idx_artefact_versions_entity_type ON public.artefact_versions USING btree (entity_type, entity_id, artefact_type_id);
CREATE INDEX idx_artefact_versions_org_generated ON public.artefact_versions USING btree (org_id, generated_at DESC);
CREATE UNIQUE INDEX uq_benchmark_ranges_global ON public.benchmark_ranges USING btree (project_type, complexity_level) WHERE (org_id IS NULL);
CREATE UNIQUE INDEX uq_benchmark_ranges_org ON public.benchmark_ranges USING btree (org_id, project_type, complexity_level) WHERE (org_id IS NOT NULL);
CREATE INDEX idx_budgets_org_project ON public.budgets USING btree (org_id, project_id);
CREATE INDEX idx_generation_runs_correlation ON public.generation_runs USING btree (correlation_id);
CREATE INDEX idx_generation_runs_entity ON public.generation_runs USING btree (entity_type, entity_id, created_at DESC);
CREATE INDEX idx_generation_runs_org_created ON public.generation_runs USING btree (org_id, created_at DESC);
CREATE INDEX idx_generation_runs_org_status ON public.generation_runs USING btree (org_id, status);
CREATE INDEX idx_input_quality_assessments_entity ON public.input_quality_assessments USING btree (entity_type, entity_id);
CREATE INDEX idx_input_quality_assessments_run ON public.input_quality_assessments USING btree (run_id);
CREATE UNIQUE INDEX ux_os_scope_list_technology_code ON public.os_scope_list_technology USING btree (code);
CREATE INDEX idx_programmes_org ON public.programmes USING btree (org_id);
CREATE UNIQUE INDEX uq_project_business_case_options_sort ON public.project_business_case_options USING btree (org_id, project_id, sort_order);
CREATE INDEX idx_projects_org ON public.projects USING btree (org_id);
CREATE INDEX idx_projects_org_stage ON public.projects USING btree (org_id, pipeline_stage);
CREATE INDEX idx_projects_programme ON public.projects USING btree (programme_id);
CREATE UNIQUE INDEX uq_rag_thresholds_global_active ON public.rag_thresholds USING btree (is_active) WHERE ((org_id IS NULL) AND (is_active = true));
CREATE UNIQUE INDEX uq_rag_thresholds_org_active ON public.rag_thresholds USING btree (org_id) WHERE ((org_id IS NOT NULL) AND (is_active = true));
CREATE INDEX idx_risks_org_project ON public.risks USING btree (org_id, project_id);
CREATE INDEX idx_risks_org_score ON public.risks USING btree (org_id, risk_score DESC);
CREATE INDEX idx_risks_project_status ON public.risks USING btree (project_id, status);
CREATE INDEX idx_task_deps_pred ON public.task_dependencies USING btree (predecessor_task_id);
CREATE INDEX idx_task_deps_succ ON public.task_dependencies USING btree (successor_task_id);
CREATE INDEX idx_tasks_project ON public.tasks USING btree (project_id);
CREATE INDEX idx_tranches_project ON public.tranches USING btree (project_id);
CREATE INDEX idx_user_org_roles_org ON public.user_org_roles USING btree (org_id);
CREATE INDEX idx_user_org_roles_user ON public.user_org_roles USING btree (user_id);
